spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.31.150.254:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 6666
com:
  baidu:
    name: 中国加油
    age: 16

